[package]
name = "fs"
version = "0.1.0"
edition = "2024"

[dependencies]
ignore = "0.4"
notify = "8.2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }
source_fast_core = { path = "../core", package = "core" }
tracing = "0.1"
rayon = "1.10"
gix = "0.69"
